// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvf3HXYF-nDqGt0MZf_wZCFrPLrNqcy_A',
    appId: '1:47810367952:web:73a7d2450cab6d40b2a9d5',
    messagingSenderId: '47810367952',
    projectId: 'rablo-rablo',
    authDomain: 'rablo-rablo.firebaseapp.com',
    storageBucket: 'rablo-rablo.firebasestorage.app',
    measurementId: 'G-GZ6R1BBEPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFWrpcZQjbgWRwvoNPxdgXBM9w5yQL3M',
    appId: '1:47810367952:android:2b12ecb44cba3a9eb2a9d5',
    messagingSenderId: '47810367952',
    projectId: 'rablo-rablo',
    storageBucket: 'rablo-rablo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIV6ozoS15TvsvTJ2Rep-8bMBvNftwEOo',
    appId: '1:47810367952:ios:af9aa6ec0e63631eb2a9d5',
    messagingSenderId: '47810367952',
    projectId: 'rablo-rablo',
    storageBucket: 'rablo-rablo.firebasestorage.app',
    iosBundleId: 'com.rablo.fitness.fitnessAppClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIV6ozoS15TvsvTJ2Rep-8bMBvNftwEOo',
    appId: '1:47810367952:ios:af9aa6ec0e63631eb2a9d5',
    messagingSenderId: '47810367952',
    projectId: 'rablo-rablo',
    storageBucket: 'rablo-rablo.firebasestorage.app',
    iosBundleId: 'com.rablo.fitness.fitnessAppClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvf3HXYF-nDqGt0MZf_wZCFrPLrNqcy_A',
    appId: '1:47810367952:web:d4117d23cf8563b2b2a9d5',
    messagingSenderId: '47810367952',
    projectId: 'rablo-rablo',
    authDomain: 'rablo-rablo.firebaseapp.com',
    storageBucket: 'rablo-rablo.firebasestorage.app',
    measurementId: 'G-Y91G8D2ZX7',
  );
}
